# Generated by Django 4.0.5 on 2022-06-15 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('auspicia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('siglas', models.CharField(max_length=5)),
                ('twiiter', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('posicion', models.CharField(max_length=5)),
                ('numero', models.IntegerField()),
                ('sueldo', models.IntegerField()),
                ('equipofut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipoDeFutbol', to='futbolec.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='CampeonatoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elcampeonato', to='futbolec.campeonato')),
                ('equipo_de_fut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elequipo', to='futbolec.equipo')),
            ],
        ),
    ]
